### ISSUE TITLE
Problem with bryntum touch scheduler

### ISSUE THREAD

**Issue by charlsagente** [MaximGB/senchacmd-customlibs#2]
I´m getting a lot of errors trying to compile my project. 

[ERR] The following error occurred while executing this line:
[path].sencha\app\build-impl.xml:378
: The following error occurred while executing this line:
[path].sencha\app\init-impl.xml:303:
 java.lang.ClassCastException: com.sencha.tools.compiler.ast.js.Name cannot be c
ast to com.sencha.tools.compiler.ast.js.ObjectLiteral

This is the part of my customlibs in app.json

"customlibs" : [{

```
// Classpath to add to application classpath list
"classpath" : "scheduler",

// Javascript file or files to append/prepend to the resulting JS file
// the option might be given as an array of objects as well
"js" : {

    // Path to a file relative to the current project directory or absolute
   // "prepend" : "scheduler/touch-scheduler-all-debug.js",             

    // Path to a file relative to the current project directory or absolute
    "append"  : "scheduler/touch-scheduler-all-debug.js"
},

// CSS file or files to append to the resulting CSS file
// the option might be given as an array of objects as well
"css" : {

    // Path to a file relative to the current project directory or absolute
    "path" : "scheduler/resources/css/touch-scheduler-all-debug.css",

    // Replacement to execute during the concatenation, might be required to properly adjust image/font
    // URLs to new CSS file base directory
    "replace" : {

        // Regular expression given as a string
        "from" : "\\.\\./images",

        // Substitution pattern
        "to"   : "scheduler"
    }
}, 
```

Could you help me find what am i doing wrong please?

**Comment by MaximGB** [comment]
Hi, please provide as much information about your development environment as possible:
- what secha cmd version do you use?
- which framework do you use (Ext or Touch) and which particular version of it?
- what's your OS name and version?

**Comment by charlsagente** [comment]
Thanks for responding:

Sencha CMD 5.1.3.61
Sencha Touch 2.1-gpl
Windows 7 64 bit.

I´m trying to integrate Bryntum Touch Scheduler 1.0.9


This is my new configuration:

"customlibs" : [{

    // Classpath to add to application classpath list
    //"classpath" : "scheduler",

    // Javascript file or files to append/prepend to the resulting JS file
    // the option might be given as an array of objects as well
    "js" : {

        // Path to a file relative to the current project directory or absolute
       // "prepend" : "scheduler/touch-scheduler-all-debug.js",             

        // Path to a file relative to the current project directory or absolute
        "append"  : "scheduler/touch-scheduler-all-debug.js"
    },

    // CSS file or files to append to the resulting CSS file
    // the option might be given as an array of objects as well
    "css" : {

        // Path to a file relative to the current project directory or absolute
        "path" : "scheduler/resources/css/touch-scheduler-all-debug.css",

        // Replacement to execute during the concatenation, might be required to properly adjust image/font
        // URLs to new CSS file base directory
        "replace" : {

            // Regular expression given as a string
            "from" : "\\.\\./images",

            // Substitution pattern
            "to"   : "scheduler"
        }
    },

    // Resources to copy
    // the option might be given as an array of objects as well
    "resources" : {

        // Path to a library's resources directory relative to the current project directory or absolute
        "from"    : "scheduler/resources",

        // Destination path
        "to"      : "build/production/${app.name}/resources/scheduler",

        // Glob file patterns to include
        "include" : "*",

        // Glob file patterns to exclude
        "exclude" : ".*"
    }
}]


And now im getting this error:



[ERR] The following error occurred while executing this line:
C:\Users\lenovo\Documents\Stuff\Campus\scheduler2\.sencha\app\build-impl.xml:284
: The following error occurred while executing this line:
C:\Users\lenovo\Documents\Stuff\Campus\scheduler2\customlibs.xml:313: Can't writ
e to C:\Users\lenovo\Documents\Stuff\Campus\scheduler2/build/production/sechedul
er2/resources/secheduler2-all.css

**Comment by MaximGB** [comment]
I've pushed a possible fix for the case, please pull/checkout and try again

**Comment by MaximGB** [comment]
Closing since the issue reporter hasn't given any feedback more, and I consider the issue to be solved.
